In [1]:
import numpy as np
import pandas as pd

pd.options.display.max_columns = 100

## Import datasets

In [2]:
# Source:
# https://www.kaggle.com/zygmunt/goodbooks-10k

btag = pd.read_csv("../data/book_tags.csv")
book = pd.read_csv("../data/books.csv")
rati = pd.read_csv("../data/ratings.csv")
tags = pd.read_csv("../data/tags.csv")
trea = pd.read_csv("../data/to_read.csv")

# https://www.kaggle.com/meetnaren/goodreads-best-books
bdat = pd.read_csv("../data/book_data.csv")

In [3]:
book.head(1)

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,"The Hunger Games (The Hunger Games, #1)",eng,4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...

In [4]:
rati.head(1)

   user_id  book_id  rating
0        1      258       5

In [5]:
trea.head(1)

   user_id  book_id
0        9        8

In [6]:
btag.head(1)

   goodreads_book_id  tag_id   count
0                  1   30574  167697

In [7]:
tags.head(1)

   tag_id tag_name
0       0        -

In [8]:
bdat.head(1)

,book_authors,book_desc,book_edition,book_format,book_isbn,book_pages,book_rating,book_rating_count,book_review_count,book_title,genres,image_url
0,Suzanne Collins,Winning will make you famous. Losing means cer...,NaN,Hardcover,9.78044E+12,374 pages,4.33,5519135,160706,The Hunger Games,Young Adult|Fiction|Science Fiction|Dystopia|F...,https://images.gr-assets.com/books/1447303603l...

## Cleaning

### book

In [9]:
book.isna().sum()

book_id                         0
goodreads_book_id               0
best_book_id                    0
work_id                         0
books_count                     0
isbn                          700
isbn13                        585
authors                         0
original_publication_year      21
original_title                585
title                           0
language_code                1084
average_rating                  0
ratings_count                   0
work_ratings_count              0
work_text_reviews_count         0
ratings_1                       0
ratings_2                       0
ratings_3                       0
ratings_4                       0
ratings_5                       0
image_url                       0
small_image_url                 0
dtype: int64

In [10]:
# what language are the language_code = NaN books in?
titles = list(book[book["language_code"].isna()]["title"])
titles[900:]

['A Perfect Spy',
 "Screw It, Let's Do It: Lessons In Life",
 'Revolting Rhymes',
 'The Guns of Navarone',
 'Tell-All',
 'The Lady & Sons Savannah Country Cookbook',
 'No One Writes to the Colonel and Other Stories',
 'The Climb: Tragic Ambitions on Everest',
 'An Old-Fashioned Girl',
 'Richard II',
 'Prisoner of My Desire',
 'The Book on the Taboo Against Knowing Who You Are',
 'Tampa',
 'The Unofficial Harry Potter Cookbook: From Cauldron Cakes to Knickerbocker Glory--More Than 150 Magical Recipes for Wizards and Non-Wizards Alike (Unofficial Cookbook)',
 'The Automatic Millionaire: A Powerful One-Step Plan to Live and Finish Rich',
 'Ghettoside: A True Story of Murder in America',
 'Once a Runner',
 'The Ear, the Eye, and the Arm',
 'Stay Out of the Basement  (Goosebumps, #2)',
 'One Day at Horrorland (Goosebumps, #16)',
 'Footfall',
 'Stone Soup',
 'Girl With Curious Hair',
 'The Revenge of the Baby-Sat',
 'The Secret Between Us',
 'Knife Edge (Noughts & Crosses, #2)',
 'The Cake Mix Doctor',
 'Depraved Heart (Kay Scarpetta, #23)',
 'The Education of Little Tree',
 'Positioning: The Battle for Your Mind: How to Be Seen and Heard in the Overcrowded Marketplace',
 "Rhett Butler's People",
 "The Royal Ranger (Ranger's Apprentice, #12)",
 'Freight Train',
 'The Flame and the Flower',
 "Exile's Return (Conclave of Shadows, #3)",
 'Preach My Gospel: A Guide To Missionary Service',
 'Like a Fire Burning (The Work and the Glory, #2)',
 'Contest',
 'The Greatest Generation',
 'The Minority Report',
 'Wizard at Large (Magic Kingdom of Landover, #3)',
 'Accident',
 'Pinocchio',
 'Curious George Takes a Job',
 'La casa de Bernarda Alba',
 'Streams in the Desert',
 'The Tenth Justice',
 'Stella Bain',
 'The Redemption of Althalus',
 'Crazy For You',
 'City of Bones / City of Ashes / City of Glass / City of Fallen Angels / City of Lost Souls (The Mortal Instruments, #1-5)',
 'The Tale of Mrs. Tiggy-Winkle',
 'For Love of Evil (Incarnations of Immortality, #6)',
 'Charlie Bone and the Shadow (The Children of the Red King, #7)',
 'The End of Poverty',
 'Call Me by Your Name',
 "Armageddon's Children (Genesis of Shannara, #1)",
 'On Becoming Baby Wise: Giving Your Infant the Gift of Nighttime Sleep',
 'Tawny Scrawny Lion',
 'Peace Child: An Unforgettable Story of Primitive Jungle Treachery in the 20th Century',
 'Truth Will Prevail (The Work and the Glory, #3)',
 'How I Raised Myself from Failure to Success in Selling',
 'Wicked - Piano/Vocal Arrangement',
 'Little Lord Fauntleroy',
 'Kulti',
 'Ruby Holler',
 'See You at the Top',
 'Harry Potter and Philosophy: If Aristotle Ran Hogwarts',
 'The Christmas Train',
 "One Flew Over the Cuckoo's Nest",
 'Last Orders',
 'Wife 22',
 'Before I Go',
 'Travel Team',
 'Islands in the Stream',
 'Capital',
 'April 1865: The Month That Saved America',
 'The Wheel of Time: Boxed Set  (Wheel of Time, #1-8)',
 'Social Intelligence: The New Science of Human Relationships',
 'Double Identity',
 'Miles to Go (The Walk, #2)',
 'Beach Town',
 'The Legend of Luke (Redwall, #12)',
 'Eat to Live: The Revolutionary Formula for Fast and Sustained Weight Loss',
 'The Nasty Bits: Collected Varietal Cuts, Usable Trim, Scraps, and Bones',
 'Summer of My German Soldier (Summer of My German Soldier, #1)',
 "I Do -- But I Don't",
 'Fine Things',
 'King of Foxes (Conclave of Shadows, #2)',
 'Lie Down with Lions',
 'Elizabeth: The Struggle for the Throne',
 'Skin',
 'In This Mountain (Mitford Years, #7)',
 'Code to Zero',
 'The Old Curiosity Shop',
 'Hands Of Light',
 'Succulent Wild Woman',
 'The Penderwicks on Gardam Street (The Penderwicks, #2)',
 'See Jane Date',
 'Pushing Ice',
 'The Secret Art of Dr. Seuss',
 'Unfamiliar Fishes',
 'Amy and Isabelle ',
 'Honor Among Enemies (Honor Harrington, #6)',
 'EntreLeadership: 20 Years of Practical Business Wisdom from the Trenches',
 'Become a Better You: 7 Keys to Improving Your Life Every Day',
 'Until Nico (Until, #4)',
 'The Second Ship (The Rho Agenda, #1)',
 'The Carrot Seed',
 'Relentless (The Lost Fleet, #5)',
 'Winter Stroll (Winter #2)',
 'Helmet for My Pillow',
 'Egomaniac',
 'Courageous (The Lost Fleet, #3)',
 'Ruby',
 'Messenger of Truth (Maisie Dobbs, #4)',
 'Apathy and Other Small Victories',
 'Essays and Poems',
 'Innocent Erendira and Other Stories',
 'Henry & Ramona',
 'Annabel (Delirium, #0.5)',
 'Ethics',
 'Nine Parts of Desire: The Hidden World of Islamic Women',
 'The Midnight Palace (Niebla, #2)',
 'Ya Yas in Bloom',
 'Tempting the Player (Gamble Brothers, #2)',
 'Cape Fear',
 'The Places That Scare You: A Guide to Fearlessness in Difficult Times',
 'Frida Kahlo: 1907-1954 Pain and Passion',
 'The Mistress of Spices',
 'Hard Limit (Hacker, #4)',
 'The Pretty Committee Strikes Back (The Clique, #5)',
 'Dial L for Loser (The Clique, #6)',
 'The River Why',
 'The Water-Method Man',
 'Heretic (The Grail Quest, #3)',
 'Economics in One Lesson: The Shortest & Surest Way to Understand Basic Economics',
 'Percy Jackson and the Sword of Hades (Percy Jackson and the Olympians, #4.5)',
 'The Walking Dead, Vol. 13: Too Far Gone',
 'How Should We Then Live? The Rise and Decline of Western Thought and Culture',
 'Belzhar',
 "The Covenant (Abram's Daughters, #1)",
 "Rich Dad's Guide to Investing: What the Rich Invest in That the Poor and Middle Class Do Not!",
 'Those Girls',
 'The Amateur Marriage',
 'The Voyages of Doctor Dolittle (Doctor Dolittle, #2)',
 'The Knockoff',
 'A Kiss for Little Bear (An I Can Read Book) by Minarik, Else Holmelund [1984]',
 'Zoya',
 'One Piece, Volume 38: Rocketman!! (One Piece, #38)',
 "Martha Stewart's Cupcakes: 175 Inspired Ideas for Everyone's Favorite Treat",
 'Neighbor Dearest',
 'The Art of Amy Brown',
 'Birdman (Jack Caffery, #1)',
 'Antigone',
 'Crooked Little Lies',
 'The Other Side of Dawn (Tomorrow, #7)',
 'The Tiger Who Came to Tea',
 "Without You, There Is No Us: My Time with the Sons of North Korea's Elite",
 'The Wolves of Willoughby Chase (The Wolves Chronicles, #1)',
 'The Scarlatti Inheritance',
 'The Last Days of Dogtown',
 'Money, and the Law of Attraction: Learning to Attract Wealth, Health, and Happiness',
 'Dark River (Warriors: Power of Three, #2)',
 'The Next Big Thing',
 'Inversions (Culture, #6)',
 'Turn of Mind',
 "The Discoverers: A History of Man's Search to Know His World and Himself",
 "Nothing's Fair in Fifth Grade",
 'Sea of Silver Light (Otherland, #4)',
 'Thank You for Smoking',
 'Nourishing Traditions: The Cookbook That Challenges Politically Correct Nutrition and the Diet Dictocrats',
 'The Bridge Across Forever: A True Love Story',
 'Demon Thief (The Demonata, #2)',
 "Sherlock Holmes of Baker Street: A Life of the World's First Consulting Detective",
 'Horrorstör',
 'The Prize Winner of Defiance, Ohio: How My Mother Raised 10 Kids on 25 Words or Less',
 'The Story of the Trapp Family Singers',
 'The Virgin Cure',
 "The Seven Principles for Making Marriage Work: A Practical Guide from the Country's Foremost Relationship Expert",
 'Anastasia Krupnik (Anastasia Krupnik, #1)',
 'Ladder of Years',
 'Night Light (Restoration #2)',
 'The First World War']

In [11]:
# all NaN in language_codes seem to refer to books in English.
# filling value
book["language_code"] = np.where(book["language_code"].isna(), "en", book["language_code"])

In [12]:
book["language_code"].sort_values().value_counts()

eng      6341
en-US    2070
en       1088
en-GB     257
ara        64
en-CA      58
fre        25
ind        21
spa        20
ger        13
jpn         7
per         7
por         6
pol         6
dan         3
nor         3
fil         2
ita         2
rus         1
nl          1
tur         1
rum         1
swe         1
mul         1
vie         1
Name: language_code, dtype: int64

In [13]:
# let's work only with English books
langs = ['eng', 'en-US', 'en-GB', 'en-CA', 'en']
enbook = book[book['language_code'].isin(langs)]
enbook.shape

(9814, 23)

In [14]:
enbook = enbook.astype({"isbn13":"object"})
enbook.dtypes

book_id                        int64
goodreads_book_id              int64
best_book_id                   int64
work_id                        int64
books_count                    int64
isbn                          object
isbn13                        object
authors                       object
original_publication_year    float64
original_title                object
title                         object
language_code                 object
average_rating               float64
ratings_count                  int64
work_ratings_count             int64
work_text_reviews_count        int64
ratings_1                      int64
ratings_2                      int64
ratings_3                      int64
ratings_4                      int64
ratings_5                      int64
image_url                     object
small_image_url               object
dtype: object

In [15]:
enbook.isna().sum()

book_id                        0
goodreads_book_id              0
best_book_id                   0
work_id                        0
books_count                    0
isbn                         628
isbn13                       542
authors                        0
original_publication_year     20
original_title               575
title                          0
language_code                  0
average_rating                 0
ratings_count                  0
work_ratings_count             0
work_text_reviews_count        0
ratings_1                      0
ratings_2                      0
ratings_3                      0
ratings_4                      0
ratings_5                      0
image_url                      0
small_image_url                0
dtype: int64

In [16]:
# leaving isbn, isbn13, original_publication_year and original_title as is

### bdat

In [17]:
# how is bdat?
bdat.isna().sum()

book_authors             0
book_desc             1331
book_edition         48848
book_format           1656
book_isbn            12866
book_pages            2522
book_rating              0
book_rating_count        0
book_review_count        0
book_title               0
genres                3242
image_url              683
dtype: int64

In [18]:
bdat["book_isbn"].unique()

array(['9.78044E+12', '9.78006E+12', '9.78068E+12', '9.78032E+12',
       '9.78038E+12', '9.78007E+12', '9.78045E+12', '9.78035E+12',
       '9.78053E+12', '9.78039E+12', '9.78031E+12', '9.78074E+12',
       '9.78014E+12', '9.78081E+12', '9.78067E+12', '9.78142E+12',
       '9.7804E+12', nan, '9.78016E+12', '9.78052E+12', '9.78159E+12',
       '9.78055E+12', '9.78079E+12', '9.7801E+12', '9.78077E+12',
       '9.78157E+12', '9.78019E+12', '9.78062E+12', '9.78001E+12',
       '9.78037E+12', '9.78034E+12', '9.78024E+12', '9.78075E+12',
       '9.78076E+12', '9.7814E+12', '9.78057E+12', '9.78093E+12',
       '9.78156E+12', '9.7816E+12', '9.78158E+12', '9.78E+12',
       '9.78189E+12', '9.78141E+12', '9.78161E+12', '9.7808E+12',
       '9.78043E+12', '9.78015E+12', '9.78144E+12', '9.78069E+12',
       '9.78059E+12', '9.78097E+12', '9.78096E+12', '9.78098E+12',
       '9.78184E+12', '9.78125E+12', '9.78049E+12', '9.78054E+12',
       '9.78186E+12', '9.78155E+12', '9.78092E+12', '9.78162E+12',
       '9.78058E+12', '9.78082E+12', '9.78094E+12', '9.7813E+12',
       '9.78148E+12', '9.78192E+12', '9.78145E+12', '9.78188E+12',
       '9.78352E+12', '9.7802E+12', '9.78084E+12', '9.78078E+12',
       '9.78191E+12', '9.78163E+12', '9.78193E+12', '9.78087E+12',
       '9.78194E+12', '9.78041E+12', '9.7806E+12', '9.78033E+12',
       '9.78146E+12', '9.7819E+12', '9.78023E+12', '9.78047E+12',
       '9.78185E+12', '9.79001E+12', '9.7807E+12', '9.7815E+12',
       '76783609419', '9.78088E+12', '9.78344E+12', '9.78085E+12',
       '9.78061E+12', '9.78149E+12', '9.78009E+12', '9.7885E+12',
       '9.78227E+12', '9.78147E+12', '9.78099E+12', '9.7803E+12',
       '9.78199E+12', '9.78225E+12', '9.78843E+12', '9.78151E+12',
       '9.78022E+12', '9.78056E+12', '9.78065E+12', '9.7898E+12',
       '9.7834E+12', '9.78973E+12', '9.7895E+12', '9.78086E+12',
       '9.78178E+12', '9.78987E+12', '9.78614E+12', '9.78195E+12',
       '9.78154E+12', '9.78083E+12', '9.78847E+12', '9.78152E+12',
       '9.78002E+12', '9.78174E+12', '9.78975E+12', '9.78223E+12',
       '9.78477E+12', '9.78842E+12', '9.78971E+12', '9.78202E+12',
       '9.78089E+12', '9.78938E+12', '9.78977E+12', '9.78143E+12',
       '9.78198E+12', '9.78072E+12', '9.7811E+12', '9.78345E+12',
       '97893806587', '9.78172E+12', '9.78817E+12', '9.78712E+12',
       '9.78073E+12', '9.78226E+12', '9.78881E+12', '9.78036E+12',
       '9.781E+12', '9.7884E+12', '9.78607E+12', '9.78979E+12',
       '9.7841E+12', '9.78145E+11', '9.78288E+12', '9.78844E+12',
       '9.78819E+12', '9.78134E+12', '9.78222E+12', '9.78197E+12',
       '9.78046E+12', '6.3081E+11', '9.78042E+12', '9.786E+12',
       '9.78208E+12', '9.78597E+12', '9.78095E+12', '9.7809E+12',
       '9.78051E+12', '9.78349E+12', '9.78968E+12', '9.78375E+12',
       '9.78168E+12', '9.78153E+12', '9.78813E+12', '9.78355E+12',
       '9.78207E+12', '9.78027E+12', '9.78295E+12', '9.78063E+12',
       '9.78357E+12', '9.78851E+12', '9.78021E+12', '9.78285E+12',
       '9.78179E+12', '9.78951E+12', '9.78849E+12', '9.78965E+12',
       '9.78995E+12', '9.78903E+12', '9.78029E+12', '9.78837E+12',
       '9.78071E+12', '9780615801', '9.783E+12', '9.78112E+12',
       '9.78852E+12', '9.7836E+12', '9.78229E+12', '9.78963E+12',
       '9.78028E+12', '9.78848E+12', '9.78974E+12', '9.78906E+12',
       '9.78904E+12', '9.78969E+12', '9.78026E+12', '9.78913E+12',
       '9.78131E+12', '9.78972E+12', '9.78109E+12', '9.78952E+12',
       '9.78286E+12', '9.78997E+12', '9.78988E+12', '9.78379E+12',
       '9.78885E+12', '9.78003E+12', '9.7882E+12', '9.78964E+12',
       '9.78343E+12', '9.78993E+12', '9.7892E+12', '9.78888E+12',
       '9.78384E+12', '9.78841E+12', '25986247522', '9.78025E+12',
       '9.78958E+12', '9.78839E+12', '9.7835E+12', '9.7888E+12',
       '9.78517E+12', '9.78406E+12', '9.78853E+12', '9.78939E+12',
       '9.78902E+12', '9.7837E+12', '9.78187E+12', '9.78955E+12',
       '9.71974E+12', '9.7899E+12', '9.78387E+12', '9.78935E+12',
       '9.78862E+12', '9.7827E+12', '9.78091E+12', '9.78326E+12',
       '9975745008', '9.78292E+12', '9.78064E+12', '9.78556E+12',
       '23755045362', '9.78864E+12', '20049010051', '9.78361E+12',
       '9.7896E+12', '9.78876E+12', '9.78382E+12', '9.78476E+12',
       '9.78287E+12', '9.78868E+12', '9.78818E+12', '9.78342E+12',
       '31809014745', '9.78877E+12', '9.7839E+12', '9.78315E+12',
       '9.78177E+12', '9.78578E+12', '9.78912E+12', '9.78066E+12',
       '9.78164E+12', '9.7838E+12', '9770916099', '9.78124E+12',
       '9.78341E+12', '9.78882E+12', '9.78133E+12', '9.78857E+12',
       '9.78858E+12', '9.78996E+12', '9.7857E+12', '9.78272E+12',
       '9.78602E+12', '9.78605E+12', '9.78411E+12', '9.78859E+12',
       '9.7805E+12', '9.78959E+12', '9.7832E+12', '9.78275E+12',
       '9.78603E+12', '9.78405E+12', '9.7829E+12', '9.78008E+12',
       '9.78274E+12', '9.78976E+12', '9.78404E+12', '9.78204E+12',
       '9.78335E+12', '9.78284E+12', '9.78999E+12', '9.78911E+12',
       '9.78346E+12', '9.78271E+12', '9.78983E+12', '9.78104E+12',
       '9.78802E+12', '9.78978E+12', '9.78905E+12', '9.78845E+12',
       '9.78043E+11', '9.78313E+12', '9.78831E+12', '9.78281E+12',
       '9.78606E+12', '9.78381E+12', '9.78508E+12', '9.79E+12',
       '9.78865E+12', '9.78887E+12', '9.7822E+12', '9.78854E+12',
       '9.78459E+12', '195170342', '9.78176E+12', '90129015962',
       '9.78013E+12', '9.78886E+12', '9.7887E+12', '9.78393E+12',
       '9.78981E+12', '9.78582E+12', '9.78883E+12', '9.78595E+12',
       '9.78416E+12', '9.97807E+12', '9.78276E+12', '9.7831E+12',
       '9.78364E+12', '9.78291E+12', '9.78146E+11', '9.78126E+12',
       '9.78613E+12', '9.78812E+12', '9.78116E+12', '9.78914E+12',
       '9.7818E+12', '13:9780615700', '9.78781E+12', '9.78966E+12',
       '9.78889E+12', '10:1496102266', '9.78149E+11', '9.78129E+12',
       '9.78909E+12', '9.78884E+12', '9.78409E+12', '9.78377E+12',
       '8987093428', '9.78373E+12', '9.78838E+12', '9.7886E+12',
       '9.78807E+12', '9.78233E+12', '9.78374E+12', '9.78005E+12',
       '9.78961E+12', '9.78135E+12', '9.78347E+12', '9.78917E+12',
       '9.78236E+12', '9.78137E+12', '9.78581E+12', '9.78893E+12',
       '9.78396E+12', '9.78874E+12', '9.789E+12', '9.78201E+12',
       '9.78994E+12', '9.78856E+12', '9.78832E+12', '9.78376E+12',
       '9.78577E+12', '9.78325E+12', '9770203807', '9.78415E+12',
       '9.78604E+12', '\xa0978097736462', '9.78989E+11', '9.78167E+12',
       '9.78294E+12', '9.78836E+12', '9.78398E+12', '9.78115E+12',
       '7.85342E+11', '9.78593E+12', '9.78907E+12', '9.78481E+12',
       '9.78915E+12', '9.78111E+12', '9.78954E+12', '9.78803E+12',
       '9.78235E+12', '9.78543E+12', '9.78833E+12', '9.78385E+12',
       '9.78894E+12', '9.78394E+12', '9.78919E+12', '1.3979E+12',
       '9.78989E+12', '9.78004E+12', '9.78956E+12', '9.78998E+12',
       '9.784E+12', '8.84088E+11', '9.78221E+12', '9.78383E+12',
       '9.7897E+12', '9.78329E+12', '9.78555E+12', '9.78336E+12',
       '9.7889E+12', '9.78545E+12', '9.78898E+12', 'B009NN5RJY',
       '9.78228E+12', '9.78363E+12', '9.78599E+12', '9.7894E+12',
       '9.78338E+12', '9.78237E+12', '8.84867E+11', '9.78386E+12',
       '35313109393', '9.7891E+12', '9.78869E+12', '9.78867E+12',
       '9.78057E+11', '9.78117E+12', '9.78591E+12', '9.78908E+12',
       '9.79119E+12', '5.60223E+12', '9.78982E+11', '9.78809E+12',
       '5.60397E+12', '9.78371E+12', '9.78248E+12', '9.78484E+12',
       '97814781942', '20049071762', '9.78587E+12', '76092011736',
       '9.78282E+12', '9.7998E+12', 'B00596V3OM', '9.78321E+12',
       '9.78957E+12', '9.84701E+12', '9.78273E+12', '9.78946E+12',
       '9.78539E+12', '9.78489E+12', '9.78608E+12', '9.78967E+12',
       '9.78962E+12', '9.78901E+12', '9.78289E+12', '9.78213E+12',
       '25986606336', '9.78984E+12', '9.7842E+12', '9.78596E+12',
       'B003U2RVVQ', '9.78099E+11', '9.78524E+12', '9.78378E+12',
       '9.78114E+12', '9.78986E+12', '9.78483E+12', '9.78751E+12',
       '9.78953E+12', '7.82009E+11', '9.7812E+12', '9.78575E+12',
       '9.78533E+12', '9.7878E+12', '9757663164', '9.78871E+12',
       '9.78113E+12', '9.78365E+12', '7.02727E+11', '9.78916E+12',
       '9.78314E+12', '9.7859E+12', '9.78479E+12', '9.78251E+12',
       '9.78283E+12', '9.78872E+12', '9.7823E+12', '13:9780999226',
       '9.78821E+12', '31809055007', '9.78828E+12', '9.79975E+12',
       '25986250973', '919795188', '7.8014E+11', '9.78846E+12',
       '9.78879E+12', '9.78825E+12', '7.89112E+11', '9.78209E+12',
       '9.78389E+12', '25986329112', '4.80652E+12', '8987026310',
       '9.78458E+12', '262240459', '9.78896E+12', '9.788E+12',
       '9.78861E+12', '9.78505E+12', '2.94001E+12', '9.78391E+12',
       'HSN1800000160', '9.78527E+12', '8670580810', '9.78535E+12',
       '25986210816', '9.78579E+12', '9.78454E+12', '23755023407',
       '1.23E+12', '10:1984254994', '7.23232E+11', '9.78525E+12',
       '9.7849E+12', '9.78255E+12', '9.78486E+12', '38332822748',
       '33500980626', '9.78878E+12', '7.80009E+11', '9.78522E+12',
       '9.78353E+12', '9.78128E+12', '9.78702E+12', '20049106884'],
      dtype=object)

In [19]:
# dropping book_isbn and image_url columns
# isbn values are rubbish due to bad conversion from float to object
bdat.drop(["book_isbn", "image_url"], axis=1, inplace=True)

In [20]:
bdat.dtypes

book_authors          object
book_desc             object
book_edition          object
book_format           object
book_pages            object
book_rating          float64
book_rating_count      int64
book_review_count      int64
book_title            object
genres                object
dtype: object

### Merging bdat and enbook

In [21]:
bdat["book_authors"].unique()

array(['Suzanne Collins', 'J.K. Rowling|Mary GrandPré', 'Harper Lee', ...,
       'Howard Megdal', 'Mimi Baird|Eve Claxton', 'Leah Price'],
      dtype=object)

In [22]:
enbook["authors"].unique()

array(['Suzanne Collins', 'J.K. Rowling, Mary GrandPré',
       'Stephenie Meyer', ..., 'Ian Mortimer', 'Peggy Orenstein',
       'John Keegan'], dtype=object)

In [23]:
enbook["nauthors"] = enbook["authors"].str.replace(", ", "|")
enbook["nauthors"].unique()

array(['Suzanne Collins', 'J.K. Rowling|Mary GrandPré', 'Stephenie Meyer',
       ..., 'Ian Mortimer', 'Peggy Orenstein', 'John Keegan'],
      dtype=object)

In [24]:
bdat[bdat["book_authors"].isin(enbook["nauthors"])]["book_authors"]

0                   Suzanne Collins
1        J.K. Rowling|Mary GrandPré
2                        Harper Lee
4                   Stephenie Meyer
5                      Markus Zusak
                    ...
54248              Sherrilyn Kenyon
54257                Robert Cormier
54262                 Richard Yates
54278       Kiyohiko Azuma|あずま きよひこ
54294                 Siri Hustvedt
Name: book_authors, Length: 18563, dtype: object

In [25]:
bdat[bdat["book_title"].isin(enbook["title"])]["book_title"]

2                                    To Kill a Mockingbird
3                                      Pride and Prejudice
5                                           The Book Thief
7                                              Animal Farm
8                                       Gone with the Wind
                               ...
54121                                            The Girls
54152    What Got You Here Won't Get You There: How Suc...
54162            The Amazing Adventures of Kavalier & Clay
54238                                       The Confession
54251                                          The Promise
Name: book_title, Length: 6189, dtype: object

In [26]:
ds = pd.merge(bdat, enbook, right_on=["title", "nauthors"], left_on=["book_title", "book_authors"], how="inner")
ds.shape

(4898, 34)

In [27]:
cols = ['book_authors', 'book_title', 'original_title', 'genres', 'book_desc', 'book_edition', 'book_format',
       'book_pages', 'original_publication_year', 'book_rating', 'book_rating_count', 'book_review_count',
       'book_id', 'goodreads_book_id']
ds = ds[cols]
ds

,book_authors,book_title,original_title,genres,book_desc,book_edition,book_format,book_pages,original_publication_year,book_rating,book_rating_count,book_review_count,book_id,goodreads_book_id
0,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,The unforgettable novel of a childhood in a sl...,50th Anniversary,Paperback,324 pages,1960.0,4.27,3745197,79450,4,2657
1,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,Harper Lee's Pulitzer Prize-winning masterwork...,NaN,Mass Market Paperback,309 pages,1960.0,4.27,3746569,79475,4,2657
2,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,One of a series of fiction titles for schools....,New Windmill,Hardcover,287 pages,1960.0,4.27,3746774,79478,4,2657
3,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,"An unforgettable story of the violent, intoler...",NaN,Paperback,285 pages,1960.0,4.27,3747139,79489,4,2657
4,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Classics|Fiction|Historical|Historical Fiction...,"'Shoot all the bluejays you want, if you can h...",NaN,Kindle Edition,385 pages,1960.0,4.27,3747228,79492,4,2657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4893,Mercer Mayer,I Was So Mad,I Was So Mad (Look-Look),Childrens|Picture Books|Childrens,Mercer Mayer's Little Critter is having quite ...,NaN,Paperback,24 pages,1983.0,4.22,17125,193,6498,386421
4894,Kazuo Ishiguro,When We Were Orphans,When We Were Orphans,Fiction|Historical|Historical Fiction|Mystery|...,"From the Booker Prize-winning, bestselling aut...",NaN,Paperback,336 pages,2000.0,3.47,21291,2037,6364,28923
4895,Sun Tzu|Thomas Cleary,The Art of War,孫子兵法 [Sūnzi bīngfǎ],Nonfiction|Classics|Philosophy|History|War,Here is a seminal work on the philosophy of su...,NaN,Paperback,172 pages,-500.0,3.96,247330,7816,403,10534
4896,Emma Cline,The Girls,The Girls,Fiction|Historical|Historical Fiction|Adult,Evie Boyd is desperate to be noticed. In the s...,NaN,Hardcover,355 pages,2016.0,3.47,130881,14439,1174,26893819
4897,Marshall Goldsmith|Mark Reiter,What Got You Here Won't Get You There: How Suc...,What Got You Here Won't Get You There: How Suc...,Business|Nonfiction|Leadership|Self Help|Busin...,America's most sought-after executive coach sh...,NaN,Hardcover,256 pages,2007.0,3.95,18854,625,5471,84525

In [28]:
# grouping genres into broader genres

broad_genres = ["Anthology","Art","Autobiography and biography","Business and money","Childrens","Comics and graphic novels","Computers and technology","Cookbooks, Food and Wine","Crafts, Hobbies and Home","Education and Teaching","Engineering and Transportation","Health and fitness","History","Humor and Entertainment","Law","LGBTQ and gender studies","Literature and fiction","Maths and science","Medical books","Mystery, thriller, suspense and horror","Parenting and relationships","Politics and social sciences","Reference","Religion and spirituality","Romance","Science fiction and fantasy","Self-Help","Sports and outdoors","Teen and young adult","Travel"]
genre_dict = {'Childrens':"Childrens",
 'Folk Tales':"Literature and fiction",
 'Suspense':"Mystery, thriller, suspense and horror",
 'Prayer':"Religion and spirituality",
 'Social Issues':"Politics and social sciences",
 'Graphic Novels':"Comics and graphic novels",
 'Teaching':"Education and Teaching",
 'Marriage':"Parenting and relationships",
 'Dogs':"Crafts, Hobbies and Home",
 'Germany':"Travel",
 'Southern Gothic':"Science fiction and fantasy",
 'Superheroes':"Comics and graphic novels",
 'Young Adult Fantasy':"Teen and young adult",
 'Movies':"Art",
 'College':"Education and Teaching",
 'Romantic':"Romance",
 'Plays':"Literature and fiction",
 'Catholic':"Religion and spirituality",
 'Love':"Parenting and relationships",
 'Cultural':"Politics and social sciences",
 'Media Tie In':"",
 'Money':"Business and money",
 'Relationships':"Parenting and relationships",
 'Shapeshifters':"Science fiction and fantasy",
 'Mystery':"Mystery, thriller, suspense and horror",
 'Islam':"Religion and spirituality",
 'Werewolves':"Science fiction and fantasy",
 'Memoir':"Autobiography and biography",
 'Mental Health':"Health and fitness",
 'How To':"Crafts, Hobbies and Home",
 '20th Century':"History",
 'Adoption':"Parenting and relationships",
 'Arthurian':"Science fiction and fantasy",
 'Philosophy':"Politics and social sciences",
 'Politics':"Politics and social sciences",
 'Education':"Education and Teaching",
 'Sequential Art':"Art",
 'Poetry Plays':"Literature and fiction",
 'Space Opera':"Science fiction and fantasy",
 'Juvenile':"Teen and young adult",
 'Dystopia':"Science fiction and fantasy",
 'Pirates':"Science fiction and fantasy",
 'Witches':"Science fiction and fantasy",
 'Christian Non Fiction':"Religion and spirituality",
 'Chick Lit':"Romance",
 'Evolution':"Maths and science",
 'The United States Of America':"Travel",
 'World History':"History",
 'Genetics':"Maths and science",
 'Urban':"Literature and fiction",
 'Abuse':"Self-Help",
 'Theory':"",
 'Latin American Literature':"Literature and fiction",
 'Vegan':"Cookbooks, Food and Wine",
 'English Literature':"Literature and fiction",
 'Parenting':"Parenting and relationships",
 'Steampunk':"Science fiction and fantasy",
 'Road Trip':"Humor and Entertainment",
 'Teen':"Teen and young adult",
 'Historical Romance':"Literature and fiction",
 'Greece':"Travel",
 'Buddhism':"Religion and spirituality",
 'Church History':"History",
 'Management':"Business and money",
 'Finance':"Business and money",
 'Police':"Mystery, thriller, suspense and horror",
 'Bdsm':"Parenting and relationships",
 'Ethiopia':"Travel",
 'Punk':"Art",
 'Jazz':"Art",
 'Crime':"Mystery, thriller, suspense and horror",
 'Literary Fiction':"Literature and fiction",
 'Batman':"Comics and graphic novels",
 'War':"History",
 'Academic':"Education and Teaching",
 'Womens Fiction':"Literature and fiction",
 'French Literature':"Literature and fiction",
 'Skepticism':"Politics and social sciences",
 'Fables':"Literature and fiction",
 'Currency':"Business and money",
 'Taoism':"Religion and spirituality",
 'India':"Travel",
 'Did Not Finish':"",
 'Ghosts':"Mystery, thriller, suspense and horror",
 'Drawing':"Art",
 'Personal Finance':"Business and money",
 'Portugal':"Travel",
 'Basketball':"Sports and outdoors",
 'Nutrition':"Health and fitness",
 'Literary Criticism':"Literature and fiction",
 'Gardening':"Crafts, Hobbies and Home",
 'Animals':"Crafts, Hobbies and Home",
 'Aliens':"Science fiction and fantasy",
 'Spanish Literature':"Literature and fiction",
 'Read For School':"Education and Teaching",
 'Mythology':"Religion and spirituality",
 'Anthropology':"Politics and social sciences",
 'Indian Literature':"Literature and fiction",
 'Biography Memoir':"Autobiography and biography",
 'Chemistry':"Maths and science",
 'United States':"Travel",
 'Medieval History':"History",
 'Sports Romance':"Romance",
 'Medievalism':"History",
 'Medicine':"Medical books",
 'Fairies':"Science fiction and fantasy",
 'Books About Books':"",
 'Paranormal':"Mystery, thriller, suspense and horror",
 'Mathematics':"Maths and science",
 'Denmark':"Travel",
 'Realistic Fiction':"Literature and fiction",
 'Inspirational':"Self-Help",
 'Anthologies':"Anthology",
 'Scotland':"Travel",
 'Iran':"Travel",
 'Gender Studies':"LGBTQ and gender studies",
 'Gender':"LGBTQ and gender studies",
 'Self Help':"Self-Help",
 'Personal Development':"Self-Help",
 'Sweden':"Travel",
 'European Literature':"Literature and fiction",
 'Marathi':"Politics and social sciences",
 'Transport':"Engineering and Transportation",
 'Womens':"LGBTQ and gender studies",
 'Fiction':"Literature and fiction",
 'Hinduism':"Religion and spirituality",
 'Fairy Tales':"Literature and fiction",
 'Dark':"Mystery, thriller, suspense and horror",
 'Spider Man':"Comics and graphic novels",
 'Theatre':"Literature and fiction",
 'Victorian':"History",
 'Spain':"Travel",
 '17th Century':"History",
 'Asian Literature':"Literature and fiction",
 'History':"History",
 'Autobiography':"Autobiography and biography",
 'Lovecraftian':"Science fiction and fantasy",
 'Psychology':"Politics and social sciences",
 'Italy':"Travel",
 'Vegetarian':"Cookbooks, Food and Wine",
 'Western Africa':"Travel",
 'Bangladesh':"Travel",
 'Poverty':"Politics and social sciences",
 'Japanese Literature':"Literature and fiction",
 'Sudan':"Travel",
 'Medical':"Medical books",
 'Fantasy':"Science fiction and fantasy",
 'New Age':"Religion and spirituality",
 'Comics':"Comics and graphic novels",
 'Adult':"Literature and fiction",
 'Productivity':"Self-Help",
 'Apocalyptic':"Science fiction and fantasy",
 'Business':"Business and money",
 'Military Fiction':"Literature and fiction",
 'Funny':"Humor and Entertainment",
 'Science':"Maths and science",
 'Classic Literature':"Literature and fiction",
 'Dc Comics':"Comics and graphic novels",
 'Erotica':"Romance",
 'Theology':"Religion and spirituality",
 'Sociology':"Politics and social sciences",
 'Detective':"Mystery, thriller, suspense and horror",
 'Unfinished':"",
 'Hugo Awards':"",
 'Nonfiction':"Politics and social sciences",
 'Academia':"Education and Teaching",
 'North American Hi...':"History",
 'Contemporary Romance':"Literature and fiction",
 'Dragons':"Science fiction and fantasy",
 'Cthulhu Mythos':"Science fiction and fantasy",
 'Emergency Services':"Politics and social sciences",
 'Historical':"History",
 'Outdoors':"Sports and outdoors",
 'Technology':"Computers and technology",
 'Civil War':"History",
 'Novella':"Literature and fiction",
 'Dark Fantasy':"Science fiction and fantasy",
 'Drama':"Literature and fiction",
 'Journalism':"Politics and social sciences",
 'Nobel Prize':"",
 'X Men':"Comics and graphic novels",
 'Art History':"Art",
 'Writing':"Literature and fiction",
 'School':"Education and Teaching",
 'Queer':"LGBTQ and gender studies",
 'Canadian Literature':"Literature and fiction",
 'Middle Grade':"Teen and young adult",
 'Christianity':"Religion and spirituality",
 'M M Romance':"Romance",
 '40k':"",
 'Polyamory':"Parenting and relationships",
 'Spirituality':"Religion and spirituality",
 'China':"Travel",
 'Russia':"Travel",
 'Biology':"Maths and science",
 'Gothic':"Horror and mystery",
 'Wicca':"Religion and spirituality",
 'New Adult':"Teen and young adult",
 'Turkish Literature':"Literature and fiction",
 'Alternate History':"Science fiction and fantasy",
 'Microhistory':"History",
 'Linguistics':"Politics and social sciences",
 'Kids':"Childrens",
 'Superman':"Comics and graphic novels",
 'Counselling':"Politics and social sciences",
 'Mental Illness':"Health and fitness",
 'Zen':"Religion and spirituality",
 'Physics':"Maths and science",
 'American':"Travel",
 'Christian':"Religion and spirituality",
 'Culinary':"Cookbooks, Food and Wine",
 'French Revolution':"History",
 'Latin American':"Travel",
 'Fitness':"Health and fitness",
 'Biography':"Autobiography and biography",
 'Star Wars':"Comics and graphic novels",
 'Death':"Self-Help",
 '18th Century':"History",
 'Nature':"Sports and outdoors",
 'Climbing':"Sports and outdoors",
 'Time Travel':"Science fiction and fantasy",
 'Israel':"Travel",
 'Lds':"",
 'Buisness':"Business and money",
 'Photography':"Art",
 'Space':"Maths and science",
 'Family':"Parenting and relationships",
 'Horses':"Crafts, Hobbies and Home",
 'Czech Literature':"Literature and fiction",
 'Military':"History",
 'Native Americans':"Politics and social sciences",
 'Italian Literature':"Literature and fiction",
 'Lgbt':"LGBTQ and gender studies",
 'Short Stories':"Anthology",
 'Tragedy':"Literature and fiction",
 'Baseball':"Sports and outdoors",
 'Young Adult Contemporary':"Teen and young adult",
 'Health':"Health and fitness",
 'Essays':"Anthology",
 'Sports':"Sports and outdoors",
 'Canada':"Travel",
 'Novels':"Literature and fiction",
 'Food':"Cookbooks, Food and Wine",
 'Turkish':"Travel",
 'True Crime':"Literature and fiction",
 'Clean Romance':"Romance",
 'Lesbian':"LGBTQ and gender studies",
 'Abandoned':"",
 'Christian Living':"Religion and spirituality",
 'Language':"Politics and social sciences",
 'Natural History':"Maths and science",
 'Poetry':"Poetry",
 'Vampires':"Mystery, thriller, suspense and horror",
 'Ancient':"History",
 'Sports and Games':"Sports and outdoors",
 'European History':"History",
 'Disability':"Health and fitness",
 'Criticism':"Literature and fiction",
 'Zombies':"Mystery, thriller, suspense and horror",
 'Magical Realism':"Science fiction and fantasy",
 'Football':"Sports and outdoors",
 'English History':"History",
 'Metaphysics':"Politics and social sciences",
 'Communication':"Politics and social sciences",
 'Picture Books':"Childrens",
 'Storytime':"Childrens",
 'Romantic Suspense':"Romance",
 'Adventure':"Action and adventure",
 'Christian Fiction':"Religion and spirituality",
 'Audiobook':"",
 'Rwanda':"Travel",
 'Witchcraft':"Crafts, Hobbies and Home",
 'German Literature':"Literature and fiction",
 'Art and Photography':"Art",
 'Nigeria':"Travel",
 '19th Century':"History",
 'Urban Fantasy':"Science fiction and fantasy",
 'Roman':"History",
 'Church':"Religion and spirituality",
 'African Literature':"Literature and fiction",
 'Social Science':"Politics and social sciences",
 'Africa':"Travel",
 'Reference':"Reference",
 'Paranormal Romance':"Science fiction and fantasy",
 'Epic Fantasy':"Science fiction and fantasy",
 'Scandinavian Literature':"Literature and fiction",
 'American History':"History",
 'Leadership':"Personal development",
 'Engineering':"Engineering and Transportation",
 'Science Fiction Fantasy':"Science fiction and fantasy",
 'Vegetarianism':"Cookbooks, Food and Wine",
 'Australia':"Travel",
 'Gay':"LGBTQ and gender studies",
 'Judaism':"Religion and spirituality",
 'Book Club':"Literature and fiction",
 'Religion':"Religion and spirituality",
 'Humanities':"Politics and social sciences",
 'High Fantasy':"Science fiction and fantasy",
 'Popular Science':"Maths and science",
 'Romance':"Romance",
 'Irish Literature':"Literature and fiction",
 'Faith':"Religion and spirituality",
 'Comic Strips':"Comics and graphic novels",
 'Social Movements':"Politics and social sciences",
 'Art':"Art",
 'True Story':"History",
 'Brain':"Maths and science",
 'Geology':"Maths and science",
 'Neuroscience':"Maths and science",
 'Combat':"Sports and outdoors",
 'Mountaineering':"Sports and outdoors",
 'Comedy':"Humor and Entertainment",
 'Swedish Literature':"Literature and fiction",
 'American Revolution':"History",
 'Birds':"Crafts, Hobbies and Home",
 'Christmas':"Crafts, Hobbies and Home",
 'Psychological Thriller':"Mystery, thriller, suspense and horror",
 'Spanish Civil War':"History",
 'Espionage':"Mystery, thriller, suspense and horror",
 'African American':"Politics and social sciences",
 'Regency':"History",
 'Terrorism':"History",
 'World War II':"History",
 'Southern':"History",
 'Speculative Fiction':"Science fiction and fantasy",
 'Shojo':"Comics and graphic novels",
 'Russian Literature':"Literature and fiction",
 'Horror':"Mystery, thriller, suspense and horror",
 'Cookbooks':"Cookbooks, Food and Wine",
 'Political Science':"Politics and social sciences",
 'Pop Culture':"Humor and Entertainment",
 'Games':"Humor and Entertainment",
 'Social Justice':"Politics and social sciences",
 'Psychoanalysis':"Politics and social sciences",
 'Travel':"Travel",
 'Astronomy':"Maths and science",
 'Polygamy':"LGBTQ and gender studies",
 'World War I':"History",
 'Architecture':"Art",
 'Contemporary':"History",
 'Zimbabwe':"Travel",
 'Eastern Africa':"Travel",
 'Weird Fiction':"Literature and fiction",
 'France':"Travel",
 'Law':"Law",
 'British Literature':"Literature and fiction",
 'Economics':"Business and money",
 'Sexuality':"Parenting and relationships",
 'Graphic Novels Comics':"Comics and graphic novels",
 'Ancient History':"History",
 'Americana':"History",
 'Video Games':"Humor and Entertainment",
 'Paganism':"Religion and spirituality",
 'Holocaust':"History",
 'Mystery Thriller':"Mystery, thriller, suspense and horror",
 'Jewish':"Religion and spirituality",
 'African American Literature':"Literature and fiction",
 'Classical Studies':"History",
 'Entrepreneurship':"Personal development",
 'Survival':"Sports and outdoors",
 'Egypt':"Travel",
 'Southern Africa':"Travel",
 'Rabbits':"Crafts, Hobbies and Home",
 'Holiday':"Personal development",
 'Presidents':"Autobiography and biography",
 'Science Fiction':"Science fiction and fantasy",
 'Asia':"Travel",
 'Eastern Philosophy':"Religion and spirituality",
 'Supernatural':"Science fiction and fantasy",
 'American Civil War':"History",
 'Historical Fiction':"Literature and fiction",
 'Environment':"Engineering and Transportation",
 'Art Design':"Art",
 'Musicians':"Art",
 'Spy Thriller':"Literature and fiction",
 'South Africa':"Travel",
 'Sustainability':"Engineering and Transportation",
 'Epic':"Literature and fiction",
 'Historical Fantasy':"Science fiction and fantasy",
 'Logic':"Politics and social sciences",
 'Culture':"Politics and social sciences",
 'Action':"Literature and fiction",
 'Westerns':"Literature and fiction",
 'Folklore':"Literature and fiction",
 'Atheism':"Religion and spirituality",
 'Ireland':"Travel",
 'International Relations':"Politics and social sciences",
 'Marvel':"Comics and graphic novels",
 'Northern Africa':"Travel",
 'Noir':"Art",
 'Feminism':"Politics and social sciences",
 'Martial Arts':"Sports and outdoors",
 'Young Adult':"Teen and young adult",
 'Adult Fiction':"Literature and fiction",
 'Manga':"Comics and graphic novels",
 'Cycling':"Sports and outdoors",
 'Military History':"History",
 'Pakistan':"Travel",
 'High School':"Teen and young adult",
 'Literature':"Literature and fiction",
 'Cyberpunk':"Science fiction and fantasy",
 'Love Story':"Romance",
 'Ghost Stories':"Mystery, thriller, suspense and horror",
 'Food and Drink':"Cookbooks, Food and Wine",
 'Race':"Politics and social sciences",
 'Foodie':"Cookbooks, Food and Wine",
 'Tudor Period':"History",
 'Design':"Art",
 'Magic':"Science fiction and fantasy",
 'Comic Book':"Comics and graphic novels",
 'Cats':"Crafts, Hobbies and Home",
 'Retellings':"History",
 'New York':"Travel",
 'Food Writing':"Cookbooks, Food and Wine",
 'Portuguese Literature':"Literature and fiction",
 'Soccer':"Sports and outdoors",
 '16th Century':"History",
 'Humor':"Humor and Entertainment",
 'Legal Thriller':"Mystery, thriller, suspense and horror",
 'Glbt':"LGBTQ and gender studies",
 'Japan':"Travel",
 'Classics':"Literature and fiction",
 'Collections':"Anthology",
 'Coming Of Age':"Teen and young adult",
 'Thriller':"Mystery, thriller, suspense and horror",
 'Cooking':"Cookbooks, Food and Wine",
 'Romanticism':"Romance",
 'Music':"Art"
}

In [29]:
def categorise(lst, dct):
    """
    This function receives a list and a dictionary as input
    and returns a list where each value of the input list is replaced with the corresponding
    value on the dictionary without duplicates.
    
    Input:
    lst: a list of strings that match the keys of the dictionary
    dct: a dictionary with a mapping of the replacement values
    
    Output:
    a list of strings where each value occurs only once
    """
    keys = list(dct.keys())
    return "|".join(list(set([dct[i] for i in lst if i in keys and len(dct[i])>0])))

ds["genres"] = ds["genres"].str.split("|")
ds["genres"] = ds["genres"].map(lambda x: categorise(x, genre_dict))
ds.head()

,book_authors,book_title,original_title,genres,book_desc,book_edition,book_format,book_pages,original_publication_year,book_rating,book_rating_count,book_review_count,book_id,goodreads_book_id
0,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Literature and fiction|History|Education and T...,The unforgettable novel of a childhood in a sl...,50th Anniversary,Paperback,324 pages,1960.0,4.27,3745197,79450,4,2657
1,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Literature and fiction|History|Education and T...,Harper Lee's Pulitzer Prize-winning masterwork...,NaN,Mass Market Paperback,309 pages,1960.0,4.27,3746569,79475,4,2657
2,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Literature and fiction|History|Education and T...,One of a series of fiction titles for schools....,New Windmill,Hardcover,287 pages,1960.0,4.27,3746774,79478,4,2657
3,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Literature and fiction|History|Education and T...,"An unforgettable story of the violent, intoler...",NaN,Paperback,285 pages,1960.0,4.27,3747139,79489,4,2657
4,Harper Lee,To Kill a Mockingbird,To Kill a Mockingbird,Literature and fiction|History|Education and T...,"'Shoot all the bluejays you want, if you can h...",NaN,Kindle Edition,385 pages,1960.0,4.27,3747228,79492,4,2657

### Ratings and tags

In [30]:
rati_ds = rati[rati["book_id"].isin(ds["book_id"])]
rati_ds

         user_id  book_id  rating
1              2     4081       4
2              2      260       5
3              2     9296       5
6              2      315       3
7              2       33       4
...          ...      ...     ...
5976462    15292      854       4
5976466    35336      317       5
5976467    21879     1403       5
5976468    21879     5674       5
5976469    21879     6720       5

[2889061 rows x 3 columns]

In [31]:
enbtag = btag[btag["goodreads_book_id"].isin(ds["goodreads_book_id"])]
tags_ds = pd.merge(enbtag, tags, on="tag_id", how="inner")
tags_ds.drop("tag_id", axis=1, inplace=True)
tags_ds

        goodreads_book_id  count           tag_name
0                       8   2823            to-read
1                      13  75870            to-read
2                      21  33603            to-read
3                      24   1009            to-read
4                      26  27858            to-read
...                   ...    ...                ...
396589           32848471     12         single-dad
396590           32848471     10       best-of-2017
396591           32848471      9    kickass-heroine
396592           32848471      7  workplace-romance
396593           32848471      7   talk-dirty-to-me

[396594 rows x 3 columns]

### Working datasets

In [32]:
ds.to_csv("../data/_clean_books.csv")
rati_ds.to_csv("../data/_clean_ratings.csv")
tags_ds.to_csv("../data/_clean_tags.csv")